apiVersion: v1
kind: Service
metadata: # kpt-merge: kuard/kuard-srv
  name: kuard-srv
  namespace: kuard
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|kuard|kuard-srv'
spec:
  type: LoadBalancer
  selector:
    app: kuard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
